# Generated by Django 4.1.2 on 2022-11-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Recibido', 'Recibido')], default='Recibido', max_length=10)),
                ('residencia', models.CharField(max_length=10)),
                ('destinatario', models.CharField(max_length=50)),
                ('f_recepcion', models.DateTimeField()),
                ('f_entrega', models.DateTimeField()),
                ('remitente', models.CharField(max_length=50)),
                ('conserje', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=10)),
                ('dueño', models.CharField(max_length=50)),
                ('c_celular', models.CharField(max_length=20)),
                ('c_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
