# Generated by Django 4.1.2 on 2022-11-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_correspondencia_f_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='conserje_ent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='conserje_rec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
