# Generated by Django 4.1.2 on 2022-11-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_correspondencia_conserje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='conserje',
        ),
    ]
