# Generated by Django 4.1.2 on 2022-11-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_correspondencia_conserje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='conserje_ent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='conserje_rec',
            field=models.CharField(max_length=50),
        ),
    ]
